### ISSUE TITLE
[Bug]: Not recognizing Pathfinder 1 party sheet

### ISSUE THREAD

**Issue by Trellinane** [EddieDover/fvtt-party-sheet#27]
### Contact Details

tjrobertsp55631@gmail.com

### What happened?

Just trying to get a Pathfinder 1 party sheet together.  Tried using the example in the Template_Readme.md file under the header Extremely Basic File Example.  JSON code below.  File placed in the foundrytt/data/partysheets folder and called it pf1.json.  I keep getting the message that there are no json files for this system.  I don't know if it is user error or something with the system specifically.

Foundry version 11.315
Party Sheets 2.5.1

{
    "name": "Test Person's Pathfinder 1E Template",
    "system": "pf1",
    "author": "Test Person",
    "rows" : [
        [
            {
                "name": "Name",
                "type": "direct",
                "header": "show",
                "text": "{charactersheet} name {newline} system.details.race"
            }
        ]
    ]
}

// Note that this uses both the charactersheet and newline special keywords.

![image](https://github.com/EddieDover/fvtt-party-sheet/assets/26035193/dce293a8-e58b-4489-9703-e22bc229ee6c)
![image](https://github.com/EddieDover/fvtt-party-sheet/assets/26035193/f8302014-6a29-49ca-ad25-52b968a06ecc)

### What type of foundry hosting were you using?

Self Hosted

### Relevant console log output

```shell
There are no console errors.  The only thing in the console is indicated in the second image above.
  

Foundry VTT | Rendering PartySheetForm       foundry.js:5802
```

**Comment by EmoCthulhu** [comment]
Hrm, my half finished template still works on PF1 system 10.3, although they must have changed a few things, because race is not uutputting correctly.

**Comment by EddieDover** [comment]
I need to see the entire console log, filtered by 'fvtt-party-sheet' to know for sure if the template is even being seen/picked up/parsed.

**Comment by EddieDover** [comment]
@Trellinane I'm not sure what the exact contents of the file you created are, but if you copy pasted directly from the documentation, and your file looks like this:

```json
{
  "name": "Test Person's Pathfinder 1E Template",
  "system": "pf1",
  "author": "Test Person",
  "rows" : [
    [
      {
        "name": "Name",
        "type": "direct",
        "header": "show",
        "text": "{charactersheet} name {newline} system.details.race"
      }
    ]
  ]
}

// Note that this uses both the charactersheet and newline special keywords.
```
Then it will fail because the comment at the bottom invalidates the JSON schema.

You should see an error like this:
![image](https://github.com/EddieDover/fvtt-party-sheet/assets/464286/218ab229-bd64-4361-9f27-9cdfea6e5531)

Can you verify both your primary console log and the contents of the template file?

**Comment by EddieDover** [comment]
Problem solved. It was indeed the comment that caused the issue.
