### ISSUE TITLE
[Bug]: {s0} breaks the file

### ISSUE THREAD

**Issue by brunocalado** [EddieDover/fvtt-party-sheet#3]
### What happened?

If I add to the code bellow 
Case 1: "text": "system.wounds.value{s0} / system.wounds.max" == this will show `system.wounds.value/ 3`, but it should show `0/ 3`

Case 2:  "text": "system.wounds.value {s0} / system.wounds.max" == the file stop to work
![image](https://github.com/EddieDover/fvtt-party-sheet/assets/4999783/f95196e1-a9ad-4edd-b296-4c20fe1ddc5a)

Original and working code
```
      {
        "name": "Wounds",
        "type": "direct",
        "align": "center",
        "header": "show",
        "minwidth": 60,
        "text": "system.wounds.value / system.wounds.max"
      },
```

**Comment by EddieDover** [comment]
Can you paste the error shown in your console log?

```json
		{
        "name": "Wounds",
        "type": "direct",
        "align": "center",
        "header": "show",
        "minwidth": 60,
        "text": "system.wounds.value {s0} / {s0} system.wounds.max"
      }
```

results in

![image](https://github.com/EddieDover/fvtt-party-sheet/assets/464286/bda782af-ab92-45d0-a171-951ab3addf38)

So there may be something else going on.

**Comment by brunocalado** [comment]
> ay be something else



> ```json
> {s0}
> ```

There is no error in the console. 
After my code like yours I just got:
![image](https://github.com/EddieDover/fvtt-party-sheet/assets/4999783/643102f7-1118-42cf-826d-a5c1bbac69f3)

**Comment by brunocalado** [comment]
It worked now. I think I need to wait a little more to click the button. If I just click the button after the world load this happens. It need a little more time to load the file.

**Comment by EddieDover** [comment]
> It worked now. I think I need to wait a little more to click the button. If I just click the button after the world load this happens. It need a little more time to load the file.

I'll investigate this. I may need to hide the button until the templates have finished loading.  May I ask how you're hosting foundry? It could just be a low-system resource issue.

**Comment by brunocalado** [comment]
> > It worked now. I think I need to wait a little more to click the button. If I just click the button after the world load this happens. It need a little more time to load the file.
> 
> I'll investigate this. I may need to hide the button until the templates have finished loading. May I ask how you're hosting foundry? It could just be a low-system resource issue.

It's self hosted in a very slow computer.

Thank you, worked nice.
![image](https://github.com/EddieDover/fvtt-party-sheet/assets/4999783/d2957aba-778b-418e-af0d-0c9d7b2821a8)
