### ISSUE TITLE
[Template]: SWADE

### ISSUE THREAD

**Issue by brunocalado** [EddieDover/fvtt-party-sheet#6]
### What system is the new template for?

SWADE

### Your system template code

[swade.json](https://github.com/EddieDover/fvtt-party-sheet/files/14529636/swade.json)
![swade](https://github.com/EddieDover/fvtt-party-sheet/assets/4999783/2cb7e729-dbdd-43b6-9aa5-0294a05f552b)

### Contact Details

@mestredigital

**Comment by EddieDover** [comment]
Updated
